"""Initial

Revision ID: a1fa3b7c146b
Revises: fe0b03a1c872
Create Date: 2023-05-17 17:02:16.734086

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a1fa3b7c146b'
down_revision = 'fe0b03a1c872'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
